services:
  - type: web
    name: api-tasa-titanes
    env: python
    [cite_start]plan: free # o tu plan [cite: 120]
    
    # El Build Command ahora solo llama a nuestro script [cite: 125]
    buildCommand: ./render_build.sh

    # El Start Command DEBE modificar el PATH y luego iniciar Gunicorn [cite: 126]
    startCommand: |
      export PATH="${PATH}:/opt/render/project/.render/chrome/opt/google/chrome"; gunicorn api:app

